### ISSUE TITLE
[help] the demo repo, /sessioninfo api return 401

### ISSUE THREAD

**Issue by chenkaiC4** [supertokens/supertokens-node#132] opened 2021-05-29 03:27 UTC
sorry, i copy the issue from react lib repo to here. really need help~
------
hi, i run the demo repo at branch *emailpassword* https://github.com/supertokens/supertokens-demo-react/tree/emailpassword

*what i can do:*
- register
- login
- get userid

*what i can't do*
- call api `/sessioninfo`

**i don't modify the demo code, just set my config**

**the frontend config is below:**

``` js
SuperTokens.init({
    appInfo: {
      appName: 'test',
      websiteDomain:`http://localhost:3000`,
      apiDomain: `http://127.0.0.1:3001`,
    },
  recipeList: [
    EmailPassword.init(),
    Session.init()
  ]
});
```

**thg backend config is below:**
``` js
supertokens.init({
    supertokens: {
        connectionURI: 'https://try.supertokens.io',
      },
        appInfo: {
          appName: 'test',
          websiteDomain:`http://localhost:3000`,
          apiDomain: `http://localhost:3001`,
        },
    recipeList: [
        EmailPassword.init(),
        Session.init()
    ]
});
```

backend log
```
GET /sessioninfo 401 0.905 ms - 26
```

frontend log
```
xhr.js:177 GET http://localhost:3001/sessioninfo 401 (Unauthorized)
CallAPIView.js:18 Error: Request failed with status code 401
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:62)
```

**Comment by rishabhpoddar** [comment] 2021-05-29 04:29
closing this issue as its a duplicate of https://github.com/supertokens/supertokens-auth-react/issues/253

**Closed by rishabhpoddar** 2021-05-29 04:29 UTC
