### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#3] opened 2020-08-09 07:07 UTC
- General auth0 handler tests
- When the axios call in Auth0 handler returns 403, make sure that the API itself returns 403
- When session has expired and the auth0 handler is being called, make sure it returns the right status code

**Comment by bhumilsarvaiya** [comment] 2020-08-26 10:29
The issue is fixed in the above referenced commit.

**Closed by bhumilsarvaiya** 2020-08-26 10:29 UTC
