### ISSUE TITLE
Implement email exists API

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#47] opened 2020-11-26 12:57 UTC
## Related issue:
- https://github.com/supertokens/frontend-driver-interface/issues/3

## Email exists API
1) Extract email from GET query param
   - If does not exist, throw bad request
2) Check if the email exists and return appropriate output

## Tasks
- [x] Implement change
- [x] Tests
- [x] Manually test body parser urlencoding preset / not present with demo app

**Comment by rishabhpoddar** [comment] 2020-11-26 16:09
@jscyo I would like you to write tests for this please. 
- It's in branch 3.1
- The test file is: https://github.com/supertokens/supertokens-node/blob/3.1/test/emailpassword/emailExists.test.js
- The API spec for this is https://github.com/supertokens/frontend-driver-interface/blob/master/v1.4.0.md#url-apibasepathemailexists

**Comment by NkxxkN** [comment] 2020-11-26 20:30
I found a bug while implementing the front end:

See video reproducing https://www.loom.com/share/e0e447c868bc4127ad8f19b3332d1600

https://github.com/supertokens/supertokens-node/blob/master/lib/ts/supertokens.ts#L95

`let path = new NormalisedURLPath("", request.originalUrl);`

When request.originalUrl = "/auth/email/exists?email=john.doe%40gmail.com" will return "/email/exists"
This is because of https://github.com/supertokens/supertokens-node/blob/d4eb0437f88041e5e91f06ffed7b3b8cf9f62411/lib/ts/normalisedURLPath.ts#L68

I fixed in the front end with: https://github.com/supertokens/supertokens-auth-react/pull/73/files#diff-df9d1f81dfc8a6758dcd7191ad9fb1df452748886efb43f3f1564ea7be6611e6R57

**Comment by rishabhpoddar** [comment] 2020-11-27 06:21
Thanks for pointing it out. However, in your `domainGiven`, why are you checking against `"/"`? Cause if the input is `exists?email=john.doe%40gmail.com`, then it will not return `/exists`. Shouldn't you check against `"?"`

**Closed** 2020-12-02 04:06 UTC
